version: "1.0.0"
image: ghcr.io/danq8/neo_watcher
slug: hamh
name: Neo Watcher
description: Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
url: https://github.com/danq8/neo_watcher
panel_icon: mdi:hub
panel_title: Neo Watcher
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
